FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM python:3.10

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

COPY requirements.cuda.txt .
RUN pip install -r requirements.cuda.txt
COPY . .

ENTRYPOINT ["python", "run.py"]