FROM python:3.10

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

COPY requirements.cpu.txt .
RUN pip install -r requirements.cpu.txt
COPY . .

ENTRYPOINT [ "python", "run.py" ]
CMD ["-h"]