FROM python:3.10

ARG FACEFUSION_VERSION=1.3.1
ENV GRADIO_SERVER_NAME=0.0.0.0

WORKDIR /facefusion

RUN apt-get update
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y

COPY . .

RUN python install.py --torch cpu --onnxruntime default

ENTRYPOINT ["python", "run.py"]